language: node_js
node_js:
- '8'
- '9'
- '10'
env:
  global:
    secure: ZkMw9Z6PYS+h9Prens4JDEmVY40GykUdC4LT6lsWPsoYSA86Ls33I5Y9tpzh7Tjp8B9yStXa0v6C0WgC0Q8liySLhaWjV2a6u7j94eD1kqybN+HX8rWfEcyBkvdJRZoXuBV38AJp5xz4+WgIRuj2aslEQPh4eyTgDw63s0QHC8etQaWjzcgIMsBDufTEVpElqfjwLR3n1GkiIeqHKmhmTIxjZZ++G8dI5B09K8PqzO3CFZh1lr/K/6KHeQO+ZpCe/Y5LvYxplFW+djRLQ7DhpVxaTiPcCgJwLTT1QM9C1ZTZ7g6FWv96bQzci3DvnqPU1kUGb6tgxgfA3TQzyGQO8L2KlKp1eypln3vrqFx4iSYM7O3vN1ji/xx6FOUMcPDA2bquWv9Fwzpoku0g0LkTq8EdgCleLNJliPdFETOLBJtzvs+sB9J5NhS8Q4zQ9iN6OO2Kh6RqQaQXiiSbmHUcywnBRR+UHVEWgg2izTk6zgDE5HyvPf5mjpcwiVWqLWAGNB5LyEw1GRE1JIggM7yR4NLZv/nlubb9R+XNNrt1fPSKqrYgYjMlqjPks56wlxSiwdPYPAAbkHFyKifIhLu9ztI184zR5W7l2MVvutdWWRl8ib9Z9IHBtRm6rn+wdwvjuN+cdAQYRgmVZMwSJnSdfJpr1lZqPGwZJtSwx2smJT8=
before_script:
- npm i
script:
- npm run test
deploy:
  provider: npm
  email: mgufronefendi@gmail.com
  api_key:
    secure: QlSufjtR8XG57kZxNaIEJVC2iBjLcgbdtH8tRoDZGNx+tqYuEFqsfjBJ4l9d4xcO9UUmt5unjEEOGUG6w0sUp3wyBS14ZJiVhU0gFCzjYUGoT2tlPGN9rRUvRFDYYTKvbBb14oZuCPmiOO1ELS2DtchRX/VkbAtFNEHvRqxTF4P9aM35hBLSntFfAOue66qEZKn4vvUNDTncRjKK9BR/qonflX0KASKqfaOTr9tUBGmWIveC6Br/w/01rkZupcmbfMrb9H0Xyjk1dTQzHIzMBb8HNwmkGvow9pZthYpAm2EGxoP2egBsxKGzShJ2sCg+NfZ2Th3nA93sZzNYPouITXQHREsRW0Oa2YxwrbLOTWSE03lgXC/bq/WcIhB9DwToupRb/vMXtCo25sU9W4FiJKhLLf8leOlBNT6Kw0cVtlEcn+uxHjmFaLYvcFp7EkEXGAX+cdiacgT087RoDIL8SAk/YoOXfFU8Z9sZUBAKAvybGhRDsC94Dy+3gH8jortIjICPTV7wbhTGzsmRz4oFjIlABiX7q1DYBeRdTxYZ9/F0TJijfMfwwRGpq1hfwkxxd9B2VosYSbNlCb1QsG0pWksEaC/ymZDwyQ4v+zVQqN1TgcGM61AKmsJZ0JBGO2lShlkiUxbJLvCbDyvnLc0x8TwhjRgGowMiVcVICKGkKKk=
  on:
    tags: true
    repo: mgufrone/react-buffered-component
